version: '2'
services:
  client:
    image: node:6.11.2
    user: root
    working_dir: /src/client
    command: ./node_modules/.bin/webpack -w true
    container_name: nw_client
    tty: true
    volumes:
      - .:/src
      - node_modules:/src/client/node_modules

  pyenv:
    build:
      context: .
      dockerfile: ./ops/Dockerfile_server
    user: root
    working_dir: /src/server
    command: ./scripts/setup.sh
    container_name: nw_pyenv
    tty: true
    volumes:
      - .:/src
      - venv:/src/server/venv

  server:
    build:
      context: .
      dockerfile: ./ops/Dockerfile_server
    user: root
    env_file:
      - web.env
    working_dir: /src/server
    command: ./venv/bin/python3 manage.py runserver 0.0.0.0:8000
    container_name: nw_server
    tty: true
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      - .:/src
      - venv:/src/server/venv
    links:
      - db
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./ops/Dockerfile_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  node_modules:
  venv:
  db_data:
